version: '3.4'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    networks: 
      - hanet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${MOUNT_POINT}/homeassistant/config:/config
    ports:
      - 8123:8123 #optional
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 #optional
    restart: unless-stopped
networks:
  hanet:
    # Use a custom driver
    name: ipvlanl3
    external: true
